---
apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: git@github.com:TKVH-Apps
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAgEAz/xxUea1ohyxdKw2Juw4vmycfSVfpXpUSCev35UV6mzQs3yqhUZX
    CrjYIfXy5xp3/2VS84xdR2qKSnZicmTAAMRim5qT2oy2aQif+wRXJbzckVNU9Ah3L1LiBA
    d0+3EtwLs/csnC/p0wv9G5QWYg2a8rDzM+7DpsCGIzvo3/dMi3nwrtiAovKWg/CxKvhCh0
    hacaZyRyLPhX9ivRIzSNbp6JQEu1S1P/zfVX4NntW0YwiCJMjPIGoq30nRusTZpK++0bS0
    l8IfcQpQ31ri2svwEnz9+/3vdregS9nLddK/m6hYsGE2ShfSm3KK7A6NYBONM1yp3VLyLk
    yDFZKybw/5GtDCZJe2G/Mx23KoFIQMcepqY/v0Flg5J/paoMg3pO3MwTiKeg49CuSqb62t
    70UEwoimK9KlNL8zFiJrAxuIvz+4x19u7Rfk/lJdyyZzHniOh6MUEwJGXHiBbV2XWyxjQ/
    YkvABtI4wgY40Q/OLKx/O9kprQj5zUjnCs5DvmE76nLJByNSbrJvekOeAYkAD25Bu1Y9Zz
    Q5U9rupapCHdv95mfs3N2PsE485qecg9QWGfYuaqHnfldscthAy9GkPOCaxNmCHAY8oEpQ
    5LlNrw5s7ef46G3PJr8+uY75DBuuixvoCLYEnThFb4Xz+Bc6Gyqu+7teOpCrUJUFA8TzZ2
    kAAAdI3cczp93HM6cAAAAHc3NoLXJzYQAAAgEAz/xxUea1ohyxdKw2Juw4vmycfSVfpXpU
    SCev35UV6mzQs3yqhUZXCrjYIfXy5xp3/2VS84xdR2qKSnZicmTAAMRim5qT2oy2aQif+w
    RXJbzckVNU9Ah3L1LiBAd0+3EtwLs/csnC/p0wv9G5QWYg2a8rDzM+7DpsCGIzvo3/dMi3
    nwrtiAovKWg/CxKvhCh0hacaZyRyLPhX9ivRIzSNbp6JQEu1S1P/zfVX4NntW0YwiCJMjP
    IGoq30nRusTZpK++0bS0l8IfcQpQ31ri2svwEnz9+/3vdregS9nLddK/m6hYsGE2ShfSm3
    KK7A6NYBONM1yp3VLyLkyDFZKybw/5GtDCZJe2G/Mx23KoFIQMcepqY/v0Flg5J/paoMg3
    pO3MwTiKeg49CuSqb62t70UEwoimK9KlNL8zFiJrAxuIvz+4x19u7Rfk/lJdyyZzHniOh6
    MUEwJGXHiBbV2XWyxjQ/YkvABtI4wgY40Q/OLKx/O9kprQj5zUjnCs5DvmE76nLJByNSbr
    JvekOeAYkAD25Bu1Y9ZzQ5U9rupapCHdv95mfs3N2PsE485qecg9QWGfYuaqHnfldscthA
    y9GkPOCaxNmCHAY8oEpQ5LlNrw5s7ef46G3PJr8+uY75DBuuixvoCLYEnThFb4Xz+Bc6Gy
    qu+7teOpCrUJUFA8TzZ2kAAAADAQABAAACADyVWiTzQSExnndP2o5H7Nd7J7JEerHnCjni
    ZZaJBNM+UySVQc6EiMI0ybBKxjCPQzj/uMP8tQcif5nlFhQgSNVwXxDYXA0jQ9cgjgk+YG
    w7sTwbu/lBpgYA7Jkj2u2LMDqd0IONReGIxDR70Ky+JP+DyNUqpj+FXQasJEpzbmAEP4hy
    VHJ2FPrIxORi0wF6D0cHP+efdCqpRGYOqWLJ4hDA2VYDN5Hzq+XAe5KhqEQYE/bzlrzPmy
    Mz7Lb+4pfQQ9tSW8r4YtI59308rb3IzDLvETu5/1fhVks6qkjGGLvAiJZxwplPjMK6rgGJ
    teOcwspcq6STiQ+r6FxwE3tAYp5o0KoLMirpVhapDrKvNo0cDhc2zFNkt+qSOo27clWc7F
    h/uyGELndAomrigauXJ5dNw0ZLUUb3/srEq61Vyvt8WzAnGBbzKJ33QwRZSmHNCfD+gZVh
    22LJSW4WgsEOVWtWf7pWaXoBY+LCrX2L0n+4AZetjvRb5iZg2JwVhpzk8XWtwKui5JqMIB
    E0xhGEUFdTHS6oEekfIetJ8RZCGQf9x1WnJwtEP8OpjNGSHCStDxktWZ0H35yyGWbJl7QQ
    gutJmNFA+m/svu1+ii+nP6bxA37eT7mb/WA6C0LnfwadO9OpvlwVmwEwnMYy6bTgeszuFP
    WOfemBE0T6M+2HPGLpAAABAQCu8UvpdB2mlC0PapEP1Kg/UjuMbzVeQA5g0qRLuQ+9Jpw2
    wHc5hO/qaliLvzPgtxhnoY7icQRJqHwcrnP+LFNcpMBNbOL24uFy4bHdHN2CAgW38kfjQO
    O6JSTF/7+JJHSdc1ACHKnwHK0rULWm+lrgsfUYXrWTx+Px6zMIPqYG0Vq+PFetjRphW73b
    z8WUhiobiOMyXihNYn9u8YJ/R5gkmRR6RQV944jw7zCAo3U0fcSXZGftqIv8duH563cno5
    6Sd2wOhsoaC//ChyuDHBaeNMgW2B+aTX5HK9XL3Ku96XPGWc5yrS2JWmmGsTRG96arcMP5
    Txclmj8j8sxqB5tEAAABAQDnhLQvr2tMuIhrSToWaXlk3l7XHnWw1Gv2QZ63mqwqOpLw9E
    WQVEeBtbZOQNxYrkEAfoDe7BbS5ECWtmNWKN3Libgi+8+tqKIjMQ0M+P4zEsdh1W9/ARfr
    yRfiwRTAzsugupAKrXYs1M6BgB73HIu0rFCynAjc0wLC/ih6l1s+0OJp0Z3JP2fa+2MpzO
    0JRf3/7UntpOxdi1HLzzwYI+X1CYJmxXHHYN5ylssa6K67TycdXXn3JUsvyJIDYutzS+dd
    sjlbFtuH+XoIuec0q2ArbACjuO6+DDhyz6R1kHtbjW7DZxkaxHQvVPlZNadFCo+j7SioEe
    3nLa0vWvMb8zZfAAABAQDl+rXxjodU+qa9MWi8EMtfNE03AuW5t+kn07Y+o+1ee3lajOnl
    VU7WLTv2Eu3bp1uUy6Rr0XmCUAFNXmnHZ1NKgQAJG8WjfR1Lxmug4twW1rahgoJBaLsKf7
    h8KbGtKPAyqAZx1ZjJrgbm6EWeEhuOlxYuiYn1It8iclpD+WH8tDc4+FvCgmtGIfmxylgi
    eXZ4by+Z/bXo51FC6F/Yjsg2IyVmOv3Ug04SdpEk8D+A80eKHV93+qYjL8m500Kbxvh2+N
    A8r70qP+alQiev7mvzdycDas73MpS5+ZjABGq3PvMg7n/R3nhSKMX/CviUZWGfB/AMd0rg
    8eB5XXhHPec3AAAAEXJvb3RAazNzLW1hc3RlcjAxAQ==
    -----END OPENSSH PRIVATE KEY-----
