apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      serviceAccountName: argocd
      automountServiceAccountToken: true
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - name: custom-tools
          mountPath: /usr/local/bin/argocd-vault-plugin
          subPath: argocd-vault-plugin
        env:
        - name: AVP_TYPE
          value: "vault"
        - name: AVP_AUTH_TYPE
          value: "k8s"
        - name: AVP_K8S_MOUNT_PATH
          value: "auth/k8s-vault-csi"
        - name: AVP_K8S_ROLE
          value: "argocd"
        - name: VAULT_ADDR
          value: "http://vault.vault:8200"
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 32Mi
      initContainers:
      - name: download-tools
        image: alpine:3.8
        command: [sh, -c]
        args:
        - >-
          wget -O argocd-vault-plugin
          https://github.com/IBM/argocd-vault-plugin/releases/download/v1.4.0/argocd-vault-plugin_1.4.0_linux_amd64 &&
          chmod +x argocd-vault-plugin &&
          mv argocd-vault-plugin /custom-tools/
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
      volumes:
      - name: custom-tools
        emptyDir: {}
