---
apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: git@github.com:TKVH-Apps
  sshPrivateKey: |
    <path:apps-kv/data/argocd/config#GITHUB_PRIVATE_KEY>
---
apiVersion: v1
kind: Secret
metadata:
  name: github-creds-2
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: git@github.com:TKVH-Infra
  sshPrivateKey: |
    <path:apps-kv/data/argocd/config#GITHUB_PRIVATE_KEY>
