apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  # ArgoCD
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.1/manifests/install.yaml
  - argocd-ing.yml
  - argocd-sa.yml
#  - argocd-github-secret.yml
  - argocd-ns.yml
  - apps/
  # Argo Image Updater, don't support plugins yet...
  #- https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/v0.11.0/manifests/install.yaml
patches:
  - argocd-cm.yml
  - argocd-rbac-cm.yml
  - argocd-repo-server-deploy-patch.yml
  - argocd-server-deploy-patch.yml
