apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - argocd-ing.yml
  - argocd-sa.yml
  - apps/
patches:
  - argocd-cm.yml
  - argocd-rbac-cm.yml
  - argocd-repo-server-deploy-patch.yml
  - argocd-server-deploy-patch.yml
